version: "3.8"

services:
  nodered:
    image: guicastelo/nodered-automacao:latest
    container_name: node-red-bitcoin
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    restart: unless-stopped

volumes:
  nodered_data:
